
title: Pat Sulik Consulting
url: 'https://cownby.github.io' #'http://junlulocky.com'
baseurl: '/webPrototype-PatSulikConsulting' #change it according to your repository name



# Profile information
yourname: Pat Sulik  ## put your name
title: 'Forensic Toxicology, Fellow'  ## your title
location: Fort Collins , CO


## Social Profiles
facebook: #http://www.facebook.com  ## your facebook account url
twitter: #http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: #http://www.dribble.com  ## you dribbble account url
foursquare: #http://www.foursquare.com  ## your foursquare account url


# Update all the sections by editing the files inside _includes folder.
